// ESlint didn't like this line, but but we are keeping it as
// it's critical to the app and it part of the autogenerated content.
var express = require('express');
var router = express.Router();

//TODO: Update routes to meet the specs

router.get('/', function(req, res) {
  res.render('index', { title: 'Express' });
});

router.get('/results', function(req, res) {
  res.render('results', req);
});

router.get('/book', function(req, res) {
  res.render('book', req);
});

router.get('/success', function(req, res) {
  res.render('success', req);
});

router.get('/booking-success', function(req, res) {
  res.render('booking-success', req);
});

router.get('/signup', function(req, res) {
  res.render('signup', req);
});

router.get('/login', function(req, res) {
  res.render('login', req);
});

router.get('/signup-restaurateur', function(req, res) {
  res.render('signup-restaurateur', req);
});

router.get('/account', function(req, res) {
  res.render('account', req);
});

router.get('/account/details', function(req, res) {
  res.render('account-details', req);
});

router.get('/restaurateur/account', function(req, res) {
  res.render('restaurateur-account', req);
});

router.get('/restaurateur/account/details', function(req, res) {
  res.render('restaurateur-account-details', req);
});

router.get('/restaurateur/account/tables', function(req, res) {
  res.render('restaurateur-account-tables', req);
});

/* POST search results. */
/*router.post('/results', function(req, res) {
  //TODO: Query DB and return json object with results

  // const myCity = req.body.city;
  // console.log(myCity);
  console.log(req.body);
  res.render('results', req);
});*/

// ESlint didn't like this line, but but we are keeping it as
// it's critical to the app and it part of the autogenerated content.
module.exports = router;
